services:
  zerophone:
    build: .
    network_mode: host
    ports:
      - "8080:8080"
    volumes:
      - zerophone-data:/data
      - ./static:/app/static:ro
    command: ["./zerophone", "--addr", ":8080"]
    environment:
      - ZEROPHONE_CLUSTER=1

  zerophone-node:
    build: .
    network_mode: host
    ports:
      - "8081:8080"
    volumes:
      - zerophone-node-data:/data
    command: ["./zerophone", "--addr", ":8080"]
    environment:
      - ZEROPHONE_CLUSTER=1
    depends_on:
      - zerophone

volumes:
  zerophone-data:
  zerophone-node-data: